[package]
name = "dsz"
version = "0.1.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.29", features = ["derive"] }
dunce = "1.0.3"
num-format = "0.4.4"
rayon = "1.7.0"
walkdir = "2"
