[package]
name = "dsz"
version = "0.2.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.2", features = ["derive"] }
dunce = "1.0"
itertools = "0.11"
num-format = "0.4"
spinners = "4.1"
walkdir = "2"
